import type { Lesson } from '../../../types';

const t = String.raw;
const L = (...lines: string[]) => lines.join('\n');

export const lesson: Lesson = {
  subtopic: 'determinants-inverses',
  know: L(
    '### What a determinant is',
    '',
    t`The **determinant** of a square matrix is a single number worked out from its entries. You write it as $\det(A)$ or with straight bars, $|A|$. It tells you one big thing: whether the matrix can be "undone" (inverted). If $\det(A) = 0$ it cannot. Geometrically, $|\det(A)|$ is the factor by which the matrix stretches areas (or volumes in 3D), so $\det = 0$ means everything gets squashed flat.`,
    '',
    t`Only **square** matrices ($2 \times 2$, $3 \times 3$, ...) have determinants.`,
    '',
    t`### The $2 \times 2$ determinant`,
    '',
    t`For $A = \begin{bmatrix} a & b \\ c & d \end{bmatrix}$:`,
    '',
    t`$$\det(A) = ad - bc$$`,
    '',
    t`Leading diagonal (top-left times bottom-right) **minus** the other diagonal. Example: $\begin{vmatrix} 3 & 5 \\ 2 & 4 \end{vmatrix} = 12 - 10 = 2$. Use brackets for negative numbers: $\begin{vmatrix} 2 & -6 \\ 1 & 3 \end{vmatrix} = 2 \times 3 - \left(-6\right) \times 1 = 12$.`,
    '',
    t`### The $3 \times 3$ determinant`,
    '',
    t`Expand along the top row. Each entry is multiplied by the $2 \times 2$ determinant you get by covering its row and column (its **minor**), and the signs go $+\;-\;+$:`,
    '',
    t`$$\begin{vmatrix} a & b & c \\ d & e & f \\ g & h & i \end{vmatrix} = a(ei - fh) - b(di - fg) + c(dh - eg)$$`,
    '',
    t`Shortcuts worth knowing:`,
    '',
    t`- **Triangular or diagonal** matrix (all zeros below, or above, the diagonal): the determinant is just the product of the diagonal entries.`,
    t`- A row (or column) of zeros, two equal rows, or one row a multiple of another: the determinant is $0$.`,
    t`- If a row has zeros in it, expand along that row: zero entries kill their terms. (Signs follow the chessboard pattern starting with $+$ in the top-left.)`,
    '',
    '### Singular and invertible',
    '',
    '| $\\det(A)$ | Name | Inverse? |',
    '| --- | --- | --- |',
    '| not $0$ | invertible (non-singular) | yes, exactly one |',
    '| $0$ | singular | no inverse |',
    '',
    t`A zero **entry** does not make a matrix singular: $\begin{bmatrix} 0 & 1 \\ 1 & 0 \end{bmatrix}$ has determinant $-1$.`,
    '',
    t`### The inverse of a $2 \times 2$ matrix`,
    '',
    t`The inverse $A^{-1}$ is the matrix with $AA^{-1} = A^{-1}A = I$, where $I = \begin{bmatrix} 1 & 0 \\ 0 & 1 \end{bmatrix}$. Recipe:`,
    '',
    t`1. Find $\det(A) = ad - bc$. If it is $0$, stop: there is no inverse.`,
    t`2. **Swap** $a$ and $d$.`,
    t`3. **Change the sign** of $b$ and $c$ (leave them where they are).`,
    t`4. **Divide** every entry by the determinant.`,
    '',
    t`Always check by multiplying back: you should get $I$.`,
    '',
    '### Determinant rules',
    '',
    t`For $n \times n$ matrices $A$ and $B$:`,
    '',
    t`- $\det(AB) = \det(A)\det(B)$ (but $\det(A + B)$ has **no** simple rule)`,
    t`- $\det(kA) = k^{n}\det(A)$, because each of the $n$ rows is multiplied by $k$`,
    t`- $\det\left(A^{-1}\right) = \frac{1}{\det(A)}$ and $\det\left(A^{T}\right) = \det(A)$`,
    t`- Multiplying **one** row by $k$ multiplies the determinant by $k$; adding a multiple of one row to another changes nothing; swapping two rows changes the sign.`,
    '',
    t`### Solving linear systems: $AX = B$`,
    '',
    t`A system like $2x + y = 4$, $5x + 3y = 11$ can be written as one matrix equation: $\begin{bmatrix} 2 & 1 \\ 5 & 3 \end{bmatrix}\begin{bmatrix} x \\ y \end{bmatrix} = \begin{bmatrix} 4 \\ 11 \end{bmatrix}$. Each row of $A$ holds one equation's coefficients. If $A$ is invertible, multiply both sides on the **left** by $A^{-1}$:`,
    '',
    t`$$X = A^{-1}B$$`,
    '',
    t`Order matters because matrix multiplication is not commutative: $XA = B$ gives $X = BA^{-1}$ instead.`,
    '',
    '### How many solutions?',
    '',
    t`- $\det(A) \ne 0$: **exactly one** solution.`,
    t`- $\det(A) = 0$: **no solution** or **infinitely many**. To decide, eliminate. If you reach a contradiction such as $0 = 2$, there is no solution (parallel lines or planes). If an equation collapses to $0 = 0$, there are infinitely many.`,
    '',
    t`A linear system can never have exactly two solutions. Typical exam question: "find $k$ so the system has no unique solution" means: set $\det(A) = 0$ and solve for $k$.`,
  ),
  formulas: [
    { label: '2 by 2 determinant', tex: t`\det\begin{bmatrix} a & b \\ c & d \end{bmatrix} = ad - bc` },
    {
      label: '3 by 3 determinant (expand along the top row)',
      tex: t`\begin{vmatrix} a & b & c \\ d & e & f \\ g & h & i \end{vmatrix} = a(ei - fh) - b(di - fg) + c(dh - eg)`,
      note: 'Signs go plus, minus, plus. Each bracket is the 2 by 2 determinant left after covering that entry\'s row and column.',
    },
    { label: 'Cofactor sign pattern', tex: t`\begin{bmatrix} + & - & + \\ - & + & - \\ + & - & + \end{bmatrix}` },
    { label: 'Triangular or diagonal matrix', tex: t`\det(A) = a_{11}a_{22}\cdots a_{nn}`, note: 'Product of the diagonal entries.' },
    { label: 'Inverse of a 2 by 2 matrix', tex: t`A^{-1} = \frac{1}{ad - bc}\begin{bmatrix} d & -b \\ -c & a \end{bmatrix}`, note: 'Only exists when $ad - bc \\ne 0$.' },
    { label: 'Definition of the inverse', tex: t`AA^{-1} = A^{-1}A = I` },
    { label: 'Singular matrix', tex: t`\det(A) = 0 \iff A \text{ has no inverse}` },
    { label: 'Product rule', tex: t`\det(AB) = \det(A)\det(B)` },
    { label: 'Scalar multiple (n by n matrix)', tex: t`\det(kA) = k^{n}\det(A)` },
    { label: 'Inverse and transpose', tex: t`\det\left(A^{-1}\right) = \frac{1}{\det(A)}, \qquad \det\left(A^{T}\right) = \det(A)` },
    { label: 'Inverse of a product', tex: t`(AB)^{-1} = B^{-1}A^{-1}`, note: 'The order reverses.' },
    { label: 'Solving a linear system', tex: t`AX = B \;\Rightarrow\; X = A^{-1}B, \qquad XA = B \;\Rightarrow\; X = BA^{-1}` },
    { label: 'Number of solutions', tex: t`\det(A) \ne 0 \Rightarrow \text{exactly one}; \qquad \det(A) = 0 \Rightarrow \text{none or infinitely many}` },
  ],
  examples: [
    {
      title: 'Determinant and inverse of a 2 by 2 matrix',
      problem: t`Find $\det(A)$ and $A^{-1}$ for $A = \begin{bmatrix} 3 & 4 \\ 1 & 2 \end{bmatrix}$.`,
      steps: [
        t`Determinant: $\det(A) = 3 \times 2 - 4 \times 1 = 6 - 4 = 2$. It is not $0$, so the inverse exists.`,
        t`Swap $3$ and $2$, change the signs of $4$ and $1$: $\begin{bmatrix} 2 & -4 \\ -1 & 3 \end{bmatrix}$.`,
        t`Divide every entry by $2$: $A^{-1} = \begin{bmatrix} 1 & -2 \\ -\frac{1}{2} & \frac{3}{2} \end{bmatrix}$.`,
        t`Check: the top-left entry of $AA^{-1}$ is $3 \times 1 + 4 \times \left(-\frac{1}{2}\right) = 1$ and the top-right is $3 \times \left(-2\right) + 4 \times \frac{3}{2} = 0$. The bottom row also works, giving $I$.`,
      ],
      answer: t`$\det(A) = 2$ and $A^{-1} = \begin{bmatrix} 1 & -2 \\ -\frac{1}{2} & \frac{3}{2} \end{bmatrix}$`,
    },
    {
      title: 'A 3 by 3 determinant',
      problem: t`Find $\det(A)$ for $A = \begin{bmatrix} 2 & 1 & 3 \\ 0 & -1 & 4 \\ 1 & 2 & 1 \end{bmatrix}$.`,
      steps: [
        t`Expand along the top row with signs $+\;-\;+$: $\det(A) = 2\begin{vmatrix} -1 & 4 \\ 2 & 1 \end{vmatrix} - 1\begin{vmatrix} 0 & 4 \\ 1 & 1 \end{vmatrix} + 3\begin{vmatrix} 0 & -1 \\ 1 & 2 \end{vmatrix}$.`,
        t`First minor: $\left(-1\right) \times 1 - 4 \times 2 = -9$.`,
        t`Second minor: $0 \times 1 - 4 \times 1 = -4$.`,
        t`Third minor: $0 \times 2 - \left(-1\right) \times 1 = 1$.`,
        t`Combine: $2\left(-9\right) - 1\left(-4\right) + 3(1) = -18 + 4 + 3 = -11$.`,
      ],
      answer: t`$\det(A) = -11$`,
    },
    {
      title: 'Using the determinant rules',
      problem: t`$A$ and $B$ are $3 \times 3$ matrices with $\det(A) = 3$ and $\det(B) = -6$. Find $\det\left(2A^{T}B^{-1}\right)$.`,
      steps: [
        t`The scalar $2$ multiplies all three rows, giving a factor $2^{3} = 8$.`,
        t`Transposing does not change the determinant: $\det\left(A^{T}\right) = 3$.`,
        t`The inverse gives the reciprocal: $\det\left(B^{-1}\right) = -\frac{1}{6}$.`,
        t`Multiply everything: $8 \times 3 \times \left(-\frac{1}{6}\right) = -4$.`,
      ],
      answer: t`$-4$`,
    },
    {
      title: 'A system with a parameter',
      problem: t`For which $k$ does the system $3x - 2y = 5$, $6x + ky = 12$ have no solution?`,
      steps: [
        t`Write $A = \begin{bmatrix} 3 & -2 \\ 6 & k \end{bmatrix}$. "No solution" needs $\det(A) = 0$.`,
        t`$\det(A) = 3k - \left(-2\right) \times 6 = 3k + 12$. Setting $3k + 12 = 0$ gives $k = -4$.`,
        t`Check the constants with $k = -4$: doubling the first equation gives $6x - 4y = 10$, but the second says $6x - 4y = 12$.`,
        t`The same left-hand side cannot equal both $10$ and $12$, so the lines are parallel: no solution.`,
      ],
      answer: t`$k = -4$`,
    },
  ],
  traps: [
    t`**Adding instead of subtracting.** The $2 \times 2$ determinant is $ad - bc$, not $ad + bc$. Watch negative entries: $-\left(-6\right) \times 1 = +6$.`,
    t`**Forgetting the middle minus sign** in a $3 \times 3$ expansion. The top-row signs are $+\;-\;+$.`,
    t`**Half-doing the inverse:** swapping $a$ and $d$ but not changing the signs of $b$ and $c$ (or the other way round), or forgetting to divide by the determinant. Multiply back to check you get $I$.`,
    t`**Using $\det(kA) = k\det(A)$.** The correct rule is $k^{n}\det(A)$: for a $3 \times 3$ matrix, $\det(2A) = 8\det(A)$.`,
    t`**Thinking $\det(A) = 0$ always means "no solution".** It means "not exactly one": it could be none or infinitely many. Check the constants.`,
    t`**Putting the inverse on the wrong side.** $AX = B$ gives $X = A^{-1}B$, not $BA^{-1}$. Matrix multiplication does not commute.`,
  ],
  examTip: L(
    t`Expect questions like "find $\det(A)$", "find $A^{-1}$", "for which $k$ is $A$ singular?", "find $\det(2A^{-1}B)$" or "how many solutions does this system have?". Fast moves:`,
    '',
    t`- **Inverse options:** multiply one option by $A$ in your head (just the top-left entry is often enough to rule it out). The right one gives $I$.`,
    t`- **"Find $k$ so it is singular":** plug each option into $\det$ and see which gives $0$. That is often faster than solving.`,
    t`- **Solving $AX = B$:** substitute each option for $x, y$ into the original equations. Only the correct one satisfies all of them.`,
    t`- **Rules questions:** wrong options are usually built from $k$ instead of $k^{n}$, $\det(B)$ instead of $\frac{1}{\det(B)}$, or adding determinants. Spot those patterns.`,
    t`- **Calculator:** many calculators have a matrix mode that computes determinants and inverses. Use it to check, but know the recipe in case you have only a basic calculator.`,
  ),
};
