import type { Lesson } from '../../../types';

const know = [
  '### Powers first',
  'Everything in this topic rests on powers. In $2^5 = 32$, the number 2 is the **base**, 5 is the **power** (or exponent), and 32 is the result. Three power rules come up again and again:',
  '- Multiply: add the powers, $a^m \\times a^n = a^{m+n}$',
  '- Divide: subtract the powers, $\\frac{a^m}{a^n} = a^{m-n}$',
  '- Power of a power: multiply the powers, $(a^m)^n = a^{mn}$',
  'Also $a^0 = 1$, $a^{-n} = \\frac{1}{a^n}$ and $a^{\\frac{1}{2}} = \\sqrt{a}$.',
  '',
  '### What a logarithm is',
  'A logarithm is just a **power** written backwards. The question "2 to what power gives 32?" has the answer 5, and we write that as $\\log_2 32 = 5$.',
  '$$\\log_b x = y \\iff b^y = x$$',
  'Read $\\log_b x$ as "the power I put on $b$ to get $x$". Some quick facts follow straight from this:',
  '| Fact | Why |',
  '| --- | --- |',
  '| $\\log_b 1 = 0$ | $b^0 = 1$ |',
  '| $\\log_b b = 1$ | $b$ to the power 1 is $b$ |',
  '| $\\log_b b^k = k$ | the power is $k$ |',
  '| $\\log_9 3 = \\frac{1}{2}$ | $9^{\\frac{1}{2}} = 3$ |',
  'You can only take the log of a **positive** number: $\\log_2 0$ and $\\log_2(-4)$ do not exist, because no power of 2 is zero or negative. This matters when you solve equations.',
  '',
  '### The two special bases',
  '- $\\log x$ with no base written usually means base 10 (the **log** button on your calculator).',
  '- $\\ln x$ means base $e$, where $e \\approx 2.718$ (the **ln** button). It is called the **natural log**.',
  'The number $e$ appears whenever something grows or shrinks at a rate proportional to its size (populations, money with continuous interest, radioactive decay, medicines leaving the blood). Because $\\ln$ and $e^x$ undo each other:',
  '$$\\ln(e^x) = x \\qquad e^{\\ln x} = x$$',
  '',
  '### The log laws',
  'Each log law is a power rule in disguise. For the same base:',
  '- Product: $\\log ab = \\log a + \\log b$ (multiplying numbers adds their powers)',
  '- Quotient: $\\log \\frac{a}{b} = \\log a - \\log b$',
  '- Power: $\\log a^k = k\\log a$ (the power comes down to the front)',
  'There is **no** rule for $\\log(a + b)$ or $\\log(a - b)$. Most wrong answers in this topic come from inventing one.',
  '',
  '### Change of base',
  'Calculators only have $\\log$ and $\\ln$, so to work out something like $\\log_5 40$ use',
  '$$\\log_a x = \\frac{\\ln x}{\\ln a} = \\frac{\\log x}{\\log a}$$',
  'For example $\\log_5 40 = \\frac{\\ln 40}{\\ln 5} \\approx 2.29$. It is a **quotient** of logs, not $\\ln 40 - \\ln 5$.',
  '',
  '### Solving exponential equations (unknown in the power)',
  '1. If both sides can be written with the same base, do that and set the powers equal: $9^x = 27$ becomes $3^{2x} = 3^3$, so $x = \\frac{3}{2}$.',
  '2. Otherwise **isolate the power** and take logs of both sides: $4 \\times 3^x = 60$ gives $3^x = 15$, so $x = \\frac{\\ln 15}{\\ln 3} \\approx 2.46$.',
  '3. If you see $e^{2x}$ and $e^x$ together, it is a hidden quadratic: let $u = e^x$, so $e^{2x} = u^2$. Reject any $u \\le 0$, because $e^x$ is always positive.',
  '',
  '### Solving log equations (unknown inside the log)',
  '1. Use the log laws to squash everything into a **single** log on one side.',
  '2. Undo it: $\\log_b A = c$ becomes $A = b^c$.',
  '3. Solve the ordinary equation that is left.',
  '4. **Check every answer** in the original equation. Reject any value that makes something inside a log zero or negative.',
  '',
  '### Growth and decay models',
  'A model $N = N_0e^{kt}$ grows when $k > 0$ and decays when it is written $N = N_0e^{-kt}$ with $k > 0$. $N_0$ is the starting amount (put $t = 0$: $e^0 = 1$). To find a time: divide by $N_0$, take $\\ln$, then divide by $k$. A time must come out positive, which is a useful check.',
  '',
  'Doubling time and half-life: the time to double is $\\frac{\\ln 2}{k}$ and the half-life of a decay is also $\\frac{\\ln 2}{k}$. A quarter left means two half-lives.',
].join('\n');

export const lesson: Lesson = {
  subtopic: 'logs-exponentials',
  know,
  formulas: [
    { label: 'Definition of a logarithm', tex: '\\log_b x = y \\iff b^y = x', note: 'Only for $b > 0$, $b \\ne 1$ and $x > 0$.' },
    { label: 'Special values', tex: '\\log_b 1 = 0 \\qquad \\log_b b = 1 \\qquad \\log_b b^k = k' },
    { label: 'Product law', tex: '\\log_b (xy) = \\log_b x + \\log_b y' },
    { label: 'Quotient law', tex: '\\log_b \\left(\\frac{x}{y}\\right) = \\log_b x - \\log_b y' },
    { label: 'Power law', tex: '\\log_b \\left(x^k\\right) = k\\log_b x' },
    { label: 'Change of base', tex: '\\log_a x = \\frac{\\ln x}{\\ln a} = \\frac{\\log x}{\\log a}', note: 'Use this to evaluate any log on a calculator.' },
    { label: 'Natural log and e undo each other', tex: '\\ln\\left(e^{x}\\right) = x \\qquad e^{\\ln x} = x \\quad (x > 0)', note: '$e \\approx 2.718$ and $\\ln$ means $\\log_e$.' },
    { label: 'Solving an exponential equation', tex: 'b^{x} = c \\implies x = \\log_b c = \\frac{\\ln c}{\\ln b}' },
    { label: 'Exponential growth and decay', tex: 'N = N_0e^{kt} \\quad (\\text{growth}) \\qquad N = N_0e^{-kt} \\quad (\\text{decay})', note: '$N_0$ is the amount at $t = 0$; $k > 0$ is the rate constant.' },
    { label: 'Time to reach a level', tex: 't = \\frac{1}{k}\\ln\\left(\\frac{N}{N_0}\\right) \\quad (\\text{growth})', note: 'For decay use $t = \\frac{1}{k}\\ln\\left(\\frac{N_0}{N}\\right)$.' },
    { label: 'Doubling time and half-life', tex: 't_{\\text{double}} = t_{\\text{half}} = \\frac{\\ln 2}{k}' },
  ],
  examples: [
    {
      title: 'Evaluate using the log laws',
      problem: 'Find the exact value of $\\log_2 40 - \\log_2 5$.',
      steps: [
        'Both logs have base 2 and are subtracted, so use the quotient law: $\\log_2 40 - \\log_2 5 = \\log_2 \\frac{40}{5}$.',
        'Simplify the fraction: $\\frac{40}{5} = 8$, so the expression is $\\log_2 8$.',
        'Ask "2 to what power gives 8?": $2^3 = 8$, so $\\log_2 8 = 3$.',
      ],
      answer: '$3$',
    },
    {
      title: 'Exponential equation with different bases',
      problem: 'Solve $2^{x + 3} = 50$, giving $x$ to 3 significant figures.',
      steps: [
        '50 is not a power of 2, so take $\\ln$ of both sides: $\\ln\\left(2^{x+3}\\right) = \\ln 50$.',
        'Power law brings the power down: $(x + 3)\\ln 2 = \\ln 50$.',
        'Divide by $\\ln 2$: $x + 3 = \\frac{\\ln 50}{\\ln 2} = \\frac{3.9120}{0.6931} = 5.6439$.',
        'Subtract 3: $x = 2.6439$.',
        'Check: $2^{5.6439} \\approx 50$. Correct.',
      ],
      answer: '$x = 2.64$ (3 s.f.)',
    },
    {
      title: 'Log equation with a root to reject',
      problem: 'Solve $\\log_3 x + \\log_3(x + 6) = 3$.',
      steps: [
        'Product law: $\\log_3\\big(x(x + 6)\\big) = 3$.',
        'Undo the log: $x(x + 6) = 3^3 = 27$.',
        'Rearrange: $x^2 + 6x - 27 = 0$.',
        'Factorise: $(x + 9)(x - 3) = 0$, so $x = -9$ or $x = 3$.',
        'Domain: $\\log_3 x$ needs $x > 0$, so reject $x = -9$.',
        'Check $x = 3$: $\\log_3 3 + \\log_3 9 = 1 + 2 = 3$. Correct.',
      ],
      answer: '$x = 3$ only',
    },
    {
      title: 'Decay model: find the half-life and a time',
      problem: 'A radioactive sample has mass $M = 80e^{-0.04t}$ grams after $t$ years. (a) Find the half-life. (b) Find when the mass is 10 grams. Give answers to 1 decimal place.',
      steps: [
        '(a) Half of 80 is 40: $80e^{-0.04t} = 40$.',
        'Divide by 80: $e^{-0.04t} = 0.5$.',
        'Take $\\ln$: $-0.04t = \\ln 0.5 = -0.6931$.',
        'Divide by $-0.04$: $t = 17.33$, so the half-life is $17.3$ years.',
        '(b) $80e^{-0.04t} = 10$ gives $e^{-0.04t} = \\frac{10}{80} = 0.125$.',
        'Take $\\ln$: $-0.04t = \\ln 0.125 = -2.0794$, so $t = \\frac{2.0794}{0.04} = 51.99$.',
        'Sense check: $80 \\to 40 \\to 20 \\to 10$ is three half-lives, and $3 \\times 17.33 = 51.99$. It agrees.',
      ],
      answer: '(a) $17.3$ years (b) $52.0$ years',
    },
  ],
  traps: [
    'Inventing a law for sums: $\\log(a + b)$ is **not** $\\log a + \\log b$. Only $\\log(ab) = \\log a + \\log b$ is true.',
    'Getting the power law the wrong way round: $\\log x^2 = 2\\log x$, but $(\\log x)^2$ is something different. In $(\\log_2 x)^2 - 3\\log_2 x + 2 = 0$ you must substitute $u = \\log_2 x$, not use the power law.',
    'Writing $\\frac{\\ln a}{\\ln b} = \\ln a - \\ln b$. A quotient of logs is not a difference of logs; $\\ln a - \\ln b = \\ln \\frac{a}{b}$.',
    'Forgetting to reject invalid roots. After solving a log equation, plug each answer back in: anything that makes a log of zero or a negative number must go.',
    'Using the $\\log$ button when you need $\\ln$. To undo $e^x$ you need $\\ln$; $\\log_{10}$ gives a different (wrong) number.',
    'Taking logs before isolating the exponential. In $200e^{-0.25t} = 50$, divide by 200 first; $\\ln(200e^{-0.25t})$ is $\\ln 200 - 0.25t$, not $-0.25t \\ln 200$.',
  ],
  examTip:
    'Most questions are "solve" or "simplify", with distractors built from the mistakes above (adding inside a log, using $\\log$ instead of $\\ln$, keeping an invalid root, forgetting to undo the log at the end). Fast tactics:\n\n' +
    '- **Plug the options back in.** With a calculator, test each option in the original equation; it is often faster than solving, and it automatically exposes invalid roots (a log of a negative number gives an error).\n' +
    '- **Estimate first.** $5^x = 40$: $5^2 = 25$ and $5^3 = 125$, so $x$ is between 2 and 3. That alone often eliminates two options.\n' +
    '- **Spot the trap options.** If one option is the answer with $\\log_{10}$ and another with $\\ln$, think about which base the question uses. If two options differ only by an extra negative root, check the domain.\n' +
    '- **Sense-check models.** A time must be positive; a decaying amount must be smaller than where it started; a quarter remaining means two half-lives.\n' +
    '- For "evaluate" questions, type the expression straight into the calculator (change of base: $\\log_a x = \\frac{\\ln x}{\\ln a}$) and compare with the options.',
};
